import type { Exercise, ExerciseCategory } from '@/types/workout'

export const EXERCISES: Record<string, Exercise> = {
  'barbell-back-squat': {
    id: 'barbell-back-squat',
    name: 'Barbell Back Squat',
    category: 'compound',
    cue: 'Drive through mid-foot, chest up, depth at hip crease or below',
    youtubeUrl: 'https://www.youtube.com/watch?v=bEv6CCg2BC8',
    substitutions: [
      { name: 'Goblet Squat', why: 'Lighter load, great for mobility' },
      { name: 'Belt Squat', why: 'No spinal compression, pure legs' },
      { name: 'Leg Press', why: 'Machine option, back-friendly' },
    ],
  },
  'romanian-deadlift': {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    category: 'compound',
    cue: 'Hinge at hips, bar tracks legs, feel hamstrings stretch at bottom',
    youtubeUrl: 'https://www.youtube.com/watch?v=7j-2w4-P14I',
    substitutions: [
      { name: 'Dumbbell RDL', why: 'Easier setup, no bar grip issues' },
      { name: 'Single-Leg RDL', why: 'Unilateral, balance challenge' },
      { name: '45° Back Extension', why: 'Machine option, no grip fatigue' },
    ],
  },
  'bulgarian-split-squat': {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    category: 'compound',
    cue: 'Front knee tracks toes, back knee drops straight down, torso upright',
    youtubeUrl: 'https://www.youtube.com/watch?v=-4LVK1crLSw',
    substitutions: [
      { name: 'Reverse Lunge', why: 'Less balance demand' },
      { name: 'Walking Lunge', why: 'Dynamic, athletic' },
      { name: 'Step-Up (DB)', why: 'Single-leg, lower back friendly' },
    ],
  },
  'walking-lunge': {
    id: 'walking-lunge',
    name: 'Walking Lunge (DB or KB)',
    category: 'compound',
    cue: 'Long stride, drop straight down, push through front heel to walk',
    youtubeUrl: 'https://www.youtube.com/watch?v=eFWCn5iEbTU',
    substitutions: [
      { name: 'Reverse Lunge', why: 'Less knee stress, stationary' },
      { name: 'Bulgarian Split Squat', why: 'More stretch, stationary' },
      { name: 'Lateral Lunge (DB)', why: 'Frontal plane, adductor work' },
    ],
  },
  'nordic-hamstring-curl': {
    id: 'nordic-hamstring-curl',
    name: 'Nordic Hamstring Curl',
    category: 'isolation',
    cue: 'Lower under control with straight knees, resist the eccentric',
    youtubeUrl: 'https://www.youtube.com/watch?v=htyDuCI8cm8',
    substitutions: [
      { name: 'Seated Leg Curl', why: 'Machine option, easier to load' },
      { name: 'Slider Leg Curl', why: 'Floor-based, bodyweight' },
      { name: 'Swiss Ball Hamstring Curl', why: 'Stability challenge' },
    ],
  },
  'barbell-hip-thrust': {
    id: 'barbell-hip-thrust',
    name: 'Barbell Hip Thrust',
    category: 'compound',
    cue: 'Squeeze glutes at top, ribs down, chin tucked throughout',
    youtubeUrl: 'https://www.youtube.com/watch?v=xDmFkJxPzeM',
    substitutions: [
      { name: 'Glute Bridge (barbell)', why: 'Same movement, off the floor' },
      { name: 'Cable Pull-Through', why: 'Standing, constant tension' },
      { name: 'Hip Thrust Machine', why: 'Machine version, easier setup' },
    ],
  },
  'conventional-deadlift': {
    id: 'conventional-deadlift',
    name: 'Conventional Deadlift',
    category: 'compound',
    cue: 'Bar stays close, chest proud, drive floor away on ascent',
    youtubeUrl: 'https://www.youtube.com/watch?v=op9kVnSso6Q',
    substitutions: [
      { name: 'Trap Bar Deadlift', why: 'More upright, easier on lower back' },
      { name: 'Sumo Deadlift', why: 'Wider stance, more quads/adductors' },
      { name: 'Romanian Deadlift', why: 'Less floor pull, more hinge' },
    ],
  },
  'snatch-grip-rdl': {
    id: 'snatch-grip-rdl',
    name: 'Snatch-Grip Romanian Deadlift',
    category: 'compound',
    cue: 'Wide grip, hinge deep, keep chest open and lats engaged',
    youtubeUrl: 'https://www.youtube.com/watch?v=0ed2L2XIO9E',
    substitutions: [
      { name: 'Romanian Deadlift', why: 'Standard grip width' },
      { name: 'Dumbbell RDL', why: 'Dumbbells, no grip issue' },
      { name: '45° Back Extension', why: 'Weighted, back-friendly' },
    ],
  },
  'goblet-squat': {
    id: 'goblet-squat',
    name: 'Goblet Squat',
    category: 'compound',
    cue: 'Elbows between knees, sit back and down, full depth',
    youtubeUrl: 'https://www.youtube.com/watch?v=MxsFDhcyFyE',
    substitutions: [
      { name: 'Bodyweight Squat', why: 'No equipment needed' },
      { name: 'Dumbbell Front Squat', why: 'Heavier load, same pattern' },
      { name: 'Leg Press', why: 'Machine alternative' },
    ],
  },
  'weighted-pull-up': {
    id: 'weighted-pull-up',
    name: 'Weighted Pull-Up',
    category: 'calisthenics',
    cue: 'Dead hang start, pull to collarbone, control the descent',
    youtubeUrl: 'https://www.youtube.com/watch?v=HuuyDNGrCI8',
    substitutions: [
      { name: 'Lat Pulldown', why: 'Machine, adjustable load' },
      { name: 'Chin-Up (supinated)', why: 'More biceps, easier' },
      { name: 'Band-Assisted Pull-Up', why: 'Reduced bodyweight' },
    ],
  },
  'ring-push-up': {
    id: 'ring-push-up',
    name: 'Ring Push-Up',
    category: 'calisthenics',
    cue: 'Rings turned in, lower to chest, press through full extension',
    youtubeUrl: 'https://www.youtube.com/watch?v=b0xFZ2HtENM',
    substitutions: [
      { name: 'Push-Up (standard)', why: 'No equipment needed' },
      { name: 'Dumbbell Bench Press', why: 'Weighted, lying down' },
      { name: 'TRX Push-Up', why: 'TRX straps, similar instability' },
    ],
  },
  'ring-dip': {
    id: 'ring-dip',
    name: 'Dip (weighted if possible)',
    category: 'calisthenics',
    cue: 'Lean forward, lower to armpits, press to lockout with rings turned in',
    youtubeUrl: 'https://www.youtube.com/watch?v=yN6Q1UI_xkE',
    substitutions: [
      { name: 'Bench Dip', why: 'Easier, bodyweight' },
      { name: 'Push-Up (close grip)', why: 'Floor-based, no bars' },
      { name: 'Machine Dip', why: 'Assisted, adjustable' },
    ],
  },
  'chest-supported-db-row': {
    id: 'chest-supported-db-row',
    name: 'Chest-Supported Dumbbell Row',
    category: 'compound',
    cue: 'Squeeze shoulder blade back, row to hip, control the negative',
    youtubeUrl: 'https://www.youtube.com/watch?v=RpODPuNtZS8',
    substitutions: [
      { name: 'Barbell Bent-Over Row', why: 'Heavier, compound' },
      { name: 'Seated Cable Row', why: 'Constant tension, cables' },
      { name: 'Single-Arm DB Row', why: 'Unilateral, anti-rotation' },
    ],
  },
  'seated-cable-row': {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    category: 'compound',
    cue: 'Sit tall, pull to navel, squeeze shoulder blades together',
    youtubeUrl: 'https://www.youtube.com/watch?v=sP_4vybjVJs',
    substitutions: [
      { name: 'Chest-Supported Dumbbell Row', why: 'Free weight, DB option' },
      { name: 'Barbell Bent-Over Row', why: 'Compound, heavy' },
      { name: 'Machine Row', why: 'Guided, stable' },
    ],
  },
  'cable-face-pull': {
    id: 'cable-face-pull',
    name: 'Cable Face Pull',
    category: 'isolation',
    cue: 'Pull to ears, external rotate at top, squeeze rear delts',
    youtubeUrl: 'https://www.youtube.com/watch?v=ljgqer1ZpXg',
    substitutions: [
      { name: 'Band Face Pull', why: 'Band option, portable' },
      { name: 'Reverse Fly (DB)', why: 'Dumbbells, rear delt focus' },
      { name: 'Band Pull-Apart', why: 'Light, warmup or finisher' },
    ],
  },
  'barbell-bench-press': {
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    category: 'compound',
    cue: 'Arch and retract scapulae, lower to mid-chest, press to lockout',
    youtubeUrl: 'https://www.youtube.com/watch?v=rT7DgCr-3pg',
    substitutions: [
      { name: 'Dumbbell Bench Press', why: 'Better ROM, independent arms' },
      { name: 'Dumbbell Incline Press', why: 'Upper chest emphasis' },
      { name: 'Floor Press (DB or BB)', why: 'Shorter ROM, shoulder safe' },
    ],
  },
  'overhead-press': {
    id: 'overhead-press',
    name: 'Overhead Press',
    category: 'compound',
    cue: 'Brace mid-section, press in slight arc, lock out overhead',
    youtubeUrl: 'https://www.youtube.com/watch?v=_RlRDWO2jfg',
    substitutions: [
      { name: 'Dumbbell Shoulder Press', why: 'Independent arms, seated option' },
      { name: 'Landmine Press', why: 'Angled, shoulder-friendly' },
      { name: 'Arnold Press', why: 'Rotation, more delt activation' },
    ],
  },
  'landmine-press': {
    id: 'landmine-press',
    name: 'Landmine Press',
    category: 'compound',
    cue: 'Clean to starting position, press in arcing path, full lockout',
    youtubeUrl: 'https://www.youtube.com/shorts/gH7PDepHNck',
    substitutions: [
      { name: 'Overhead Press', why: 'Full overhead, barbell' },
      { name: 'Dumbbell Shoulder Press', why: 'Seated or standing, DBs' },
      { name: 'Machine Shoulder Press', why: 'Guided path, stable' },
    ],
  },
  'db-incline-press': {
    id: 'db-incline-press',
    name: 'Dumbbell Incline Press',
    category: 'compound',
    cue: 'Upper back tight against bench, lower with control, press up and together',
    youtubeUrl: 'https://www.youtube.com/watch?v=0t6z4Q2iHQA',
    substitutions: [
      { name: 'Barbell Incline Press', why: 'Heavier load option' },
      { name: 'Machine Incline Press', why: 'No stabilization needed' },
      { name: 'Landmine Press (kneeling)', why: 'Angled press, core engaged' },
    ],
  },
  'db-hammer-curl': {
    id: 'db-hammer-curl',
    name: 'Dumbbell Hammer Curl',
    category: 'isolation',
    cue: 'Curl with palm facing body, elbow stays tucked, full contraction at top',
    youtubeUrl: 'https://www.youtube.com/watch?v=7jqi2qWAUJk',
    substitutions: [
      { name: 'Barbell Curl', why: 'Heavier, bilateral' },
      { name: 'Cable Curl', why: 'Constant tension' },
      { name: 'Incline DB Curl', why: 'Stretched position, long head' },
    ],
  },
  'db-lateral-raise': {
    id: 'db-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    category: 'isolation',
    cue: 'Lead with elbows, slight bend, raise to shoulder height, control descent',
    youtubeUrl: 'https://www.youtube.com/watch?v=-hyAJdSFzT4',
    substitutions: [
      { name: 'Cable Lateral Raise', why: 'Constant tension at bottom' },
      { name: 'Machine Lateral Raise', why: 'Guided, easier to load' },
      { name: 'Band Lateral Raise', why: 'Portable, good for pump' },
    ],
  },
  'overhead-tricep-extension': {
    id: 'overhead-tricep-extension',
    name: 'Overhead Tricep Extension (cable)',
    category: 'isolation',
    cue: 'Elbow stays close to head, lower behind head, press to lockout',
    youtubeUrl: 'https://www.youtube.com/watch?v=IaJWPqP-Bjo',
    substitutions: [
      { name: 'Skull Crusher (BB/EZ)', why: 'Barbell, heavy triceps' },
      { name: 'Dumbbell Overhead Extension', why: 'DB alternative' },
      { name: 'Close-Grip Bench Press', why: 'Compound tricep builder' },
    ],
  },
  'box-jump': {
    id: 'box-jump',
    name: 'Box Jump (step down)',
    category: 'plyometric',
    cue: 'Swing arms hard, land soft and quiet, step down to save knees',
    youtubeUrl: 'https://www.youtube.com/watch?v=aDZoErlL1LQ',
    substitutions: [
      { name: 'Squat Jump', why: 'No box needed' },
      { name: 'Broad Jump', why: 'Horizontal power' },
      { name: 'Depth Jump', why: 'Reactive, advanced' },
    ],
  },
  'broad-jump': {
    id: 'broad-jump',
    name: 'Broad Jump',
    category: 'plyometric',
    cue: 'Dip and load, extend hips fully, land soft in athletic stance',
    youtubeUrl: 'https://www.youtube.com/watch?v=96zJo3nlmHI',
    substitutions: [
      { name: 'Box Jump', why: 'Vertical power' },
      { name: 'Squat Jump', why: 'Vertical, no distance needed' },
      { name: 'Kettlebell Swing', why: 'Hip power, loaded' },
    ],
  },
  'clap-push-up': {
    id: 'clap-push-up',
    name: 'Clap Push-Up',
    category: 'plyometric',
    cue: 'Lower fast, explode up, clap hands before landing, reset',
    youtubeUrl: 'https://www.youtube.com/watch?v=EYwWCgM198U',
    substitutions: [
      { name: 'Explosive Push-Up', why: 'Hands leave, no clap' },
      { name: 'Med Ball Chest Pass', why: 'Wall throw, upper body power' },
      { name: 'Band-Resisted Push-Up', why: 'Loaded push, explosive' },
    ],
  },
  'depth-drop': {
    id: 'depth-drop',
    name: 'Depth Drop',
    category: 'plyometric',
    cue: 'Step off box, land stiff, immediately absorb and jump',
    youtubeUrl: 'https://www.youtube.com/watch?v=DZrJpNfmIHQ',
    substitutions: [
      { name: 'Box Jump', why: 'Concentric focus' },
      { name: 'Drop Landing', why: 'Absorb only, less reactive' },
      { name: 'Broad Jump', why: 'Horizontal, no box' },
    ],
  },
  'sprint-intervals': {
    id: 'sprint-intervals',
    name: 'Sprint Intervals',
    category: 'conditioning',
    cue: 'Arms pump hard, drive knees up, max effort on each repeat',
    youtubeUrl: 'https://www.youtube.com/watch?v=sWoQS_JDHoU',
    substitutions: [
      { name: 'Bike Sprint Intervals', why: 'Low impact, same effort' },
      { name: 'Rowing Sprint Intervals', why: 'Full body, indoor' },
      { name: 'Hill Sprints', why: 'Natural incline, less hamstring risk' },
    ],
  },
  'kettlebell-swing': {
    id: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    category: 'explosive',
    cue: 'Hinge and hike, snap hips forward at apex, let KB float back',
    youtubeUrl: 'https://www.youtube.com/watch?v=jYtimecuwuw',
    substitutions: [
      { name: 'Dumbbell Swing', why: 'DB substitute' },
      { name: 'Hip Thrust (explosive)', why: 'Loaded hip extension' },
      { name: 'Cable Pull-Through', why: 'Similar hinge, constant tension' },
    ],
  },
  'farmers-carry': {
    id: 'farmers-carry',
    name: "Farmer's Carry",
    category: 'carry',
    cue: 'Stand tall, squeeze grip, walk fast with short quick steps',
    youtubeUrl: 'https://www.youtube.com/watch?v=IWxerVP5eps',
    substitutions: [
      { name: 'Suitcase Carry', why: 'Single arm, anti-lateral flexion' },
      { name: 'Overhead Carry', why: 'Shoulder stability challenge' },
      { name: 'Trap Bar Carry', why: 'Heavier load, centered' },
    ],
  },
  'turkish-get-up': {
    id: 'turkish-get-up',
    name: 'Turkish Get-Up',
    category: 'conditioning',
    cue: 'Eyes on weight, sit to half-kneel, stand tall, reverse slow',
    youtubeUrl: 'https://www.youtube.com/watch?v=jFK8FOiLa_M',
    substitutions: [
      { name: 'Windmill', why: 'Similar stability, simpler' },
      { name: 'Half Get-Up', why: 'First half only, easier' },
      { name: 'Overhead Carry', why: 'Stability + movement' },
    ],
  },
  'devils-press': {
    id: 'devils-press',
    name: "Devil's Press (DB)",
    category: 'conditioning',
    cue: 'Burpee, clean, thruster — breathe when you can, move nonstop',
    youtubeUrl: 'https://www.youtube.com/watch?v=Cwxmji-3k40',
    substitutions: [
      { name: 'Dumbbell Thruster', why: 'Squat to press, simpler' },
      { name: 'Burpee', why: 'Bodyweight, no DBs' },
      { name: 'Man Maker', why: 'Adds clean and press' },
    ],
  },
  'renegade-row': {
    id: 'renegade-row',
    name: 'Renegade Row',
    category: 'compound',
    cue: 'Plank tight, row to hip, alternate with control, breathe',
    youtubeUrl: 'https://www.youtube.com/watch?v=eGhLfe0feEs',
    substitutions: [
      { name: 'Plank Row (single DB)', why: 'One arm at a time' },
      { name: 'Push-Up + Row (alternating)', why: 'Same but separate reps' },
      { name: 'Man Maker', why: 'Adds clean and press' },
    ],
  },
  'burpee-to-pull-up': {
    id: 'burpee-to-pull-up',
    name: 'Burpee to Pull-Up',
    category: 'conditioning',
    cue: 'Chest and thighs touch floor, jump up and pull in one motion',
    youtubeUrl: 'https://www.youtube.com/watch?v=RWysgOhr0vM',
    substitutions: [
      { name: 'Burpee', why: 'No pull-up bar needed' },
      { name: "Devil's Press (DB)", why: 'DB-loaded full body' },
      { name: 'Thruster', why: 'Squat to press combo' },
    ],
  },
  'med-ball-overhead-slam': {
    id: 'med-ball-overhead-slam',
    name: 'Med Ball Overhead Slam',
    category: 'explosive',
    cue: 'Big arc overhead, slam hard into ground, use the bounce or catch',
    youtubeUrl: 'https://www.youtube.com/watch?v=gNWBGsjFeWo',
    substitutions: [
      { name: 'Ball Slam', why: 'Same but downward emphasis' },
      { name: 'Kettlebell Swing', why: 'Hip power, no slam' },
      { name: 'Battle Rope Slams', why: 'Sustained power output' },
    ],
  },
  'rotational-wall-throw': {
    id: 'rotational-wall-throw',
    name: 'Rotational Wall Throw',
    category: 'conditioning',
    cue: 'Step into throw, rotate hips, release at target wall',
    youtubeUrl: 'https://www.youtube.com/watch?v=IhIi-lDzHXw',
    substitutions: [
      { name: 'Med Ball Chest Pass', why: 'Linear, upper body' },
      { name: 'Landmine Press', why: 'Rotational component' },
    ],
  },
  'front-lever-progression': {
    id: 'front-lever-progression',
    name: 'Front Lever Progression',
    category: 'calisthenics',
    cue: 'Retract scapulae, tuck hard, hollow body position throughout',
    youtubeUrl: 'https://www.youtube.com/watch?v=eXYCKTwK9EI',
    substitutions: [
      { name: 'Hanging Knee Raise (tucked hold)', why: 'Simpler hold, build up' },
      { name: 'Ring Row (feet elevated)', why: 'Similar pull angle, easier' },
      { name: 'Dragon Flag (progression)', why: 'Bench-based, same core demand' },
    ],
  },
  'hollow-body-hold': {
    id: 'hollow-body-hold',
    name: 'Hollow Body Hold',
    category: 'mobility',
    cue: 'Lower back pressed to floor, arms by ears, hold the hollow',
    youtubeUrl: 'https://www.youtube.com/watch?v=YceIIdhzDPo',
    isTimeBased: true,
    substitutions: [
      { name: 'Dead Bug', why: 'Easier, alternating limbs' },
      { name: 'Plank', why: 'Prone, simpler setup' },
      { name: 'Ab Wheel Rollout', why: 'Rolling core challenge' },
    ],
  },
  'hanging-knee-raise': {
    id: 'hanging-knee-raise',
    name: 'Hanging Knee Raise',
    category: 'calisthenics',
    cue: 'Hang from bar, raise knees to hip crease, lower with control',
    youtubeUrl: 'https://www.youtube.com/watch?v=RD_A-Z15ER4',
    substitutions: [
      { name: 'Hanging Leg Raise', why: 'Harder, straight legs' },
      { name: "Captain's Chair Knee Raise", why: 'Padded support' },
      { name: 'Lying Leg Raise', why: 'Floor-based, no bar needed' },
    ],
  },
  'bear-crawl': {
    id: 'bear-crawl',
    name: 'Bear Crawl',
    category: 'conditioning',
    cue: 'Shoulders over hands, hips low, crawl forward alternating arms/legs',
    youtubeUrl: 'https://www.youtube.com/watch?v=vg5hegN6pk0',
    substitutions: [
      { name: 'Bear Crawl Hold', why: 'Static, no movement' },
      { name: 'Plank to Push-Up', why: 'Dynamic, tricep emphasis' },
    ],
  },
  'side-plank': {
    id: 'side-plank',
    name: 'Side Plank',
    category: 'mobility',
    cue: 'Stack hips, extend top arm, hold the side plank line',
    youtubeUrl: 'https://www.youtube.com/watch?v=茉莉',
    isTimeBased: true,
    substitutions: [
      { name: 'Copenhagen Plank', why: 'Adductor emphasis, harder' },
      { name: 'Pallof Press', why: 'Cable anti-rotation' },
      { name: 'Suitcase Carry', why: 'Walking anti-lateral flexion' },
    ],
  },
  'copenhagen-plank': {
    id: 'copenhagen-plank',
    name: 'Copenhagen Plank',
    category: 'mobility',
    cue: 'Top leg on bench, hold side plank with adductors engaged',
    substitutions: [
      { name: 'Side Plank', why: 'Easier, no bench needed' },
      { name: 'Side Plank with Hip Dip', why: 'Dynamic oblique' },
    ],
  },
  'single-leg-calf-raise': {
    id: 'single-leg-calf-raise',
    name: 'Single-Leg Calf Raise',
    category: 'isolation',
    cue: 'Rise onto toes, pause at top, lower slow to full stretch',
    youtubeUrl: 'https://www.youtube.com/watch?v=_gEx2ijsmNM',
    substitutions: [
      { name: 'Seated Calf Raise', why: 'Soleus emphasis, machine' },
      { name: 'Standing Calf Raise (machine)', why: 'Both legs, heavier load' },
    ],
  },
  // ==== NEW HangFit Hybrid Program Exercises ====
  'trap-bar-jump-squat': {
    id: 'trap-bar-jump-squat',
    name: 'Trap Bar Jump Squat',
    category: 'explosive',
    cue: 'Jump off trap bar, drive hips forward, land soft and reset',
    youtubeUrl: 'https://www.youtube.com/watch?v=9bC_6Q2K_HQ',
    substitutions: [
      { name: 'Box Jump', why: 'Same power, simpler' },
      { name: 'Squat Jump', why: 'No bar, bodyweight only' },
      { name: 'Broad Jump', why: 'Horizontal focus' },
    ],
  },
  'ring-leg-curl': {
    id: 'ring-leg-curl',
    name: 'Ring Leg Curl',
    category: 'isolation',
    cue: 'Lie under pull-up bar, curl heels to glutes, lower with control',
    youtubeUrl: 'https://www.youtube.com/watch?v=6A0_zmcKxMQ',
    substitutions: [
      { name: 'Nordic Hamstring Curl', why: 'Eccentric focus, no bar needed' },
      { name: 'Slider Leg Curl', why: 'Floor-based, bodyweight' },
      { name: 'Swiss Ball Hamstring Curl', why: 'Stability challenge' },
    ],
  },
  'reverse-nordic-curl': {
    id: 'reverse-nordic-curl',
    name: 'Reverse Nordic Curl',
    category: 'isolation',
    cue: 'Kneel and lean back, resist gravity, curl back up with quads',
    youtubeUrl: 'https://www.youtube.com/watch?v=4r3kQvhB_7E',
    substitutions: [
      { name: 'Squat (partial)', why: 'Same quad emphasis' },
      { name: 'Leg Extension', why: 'Machine quad isolation' },
      { name: 'Spanish Squat', why: 'Loaded, quad focused' },
    ],
  },
  'cossack-squat-hold': {
    id: 'cossack-squat-hold',
    name: 'Cossack Squat Hold',
    category: 'mobility',
    cue: 'Wide stance, sit lateral, knees track toes, hold bottom position',
    youtubeUrl: 'https://www.youtube.com/watch?v=2nG2A2inC6s',
    isTimeBased: true,
    substitutions: [
      { name: 'Assisted Cossack Squat', why: 'Use TRX or band for support' },
      { name: 'Lateral Lunge Hold', why: 'Less depth, static' },
      { name: 'Sumo Squat Hold', why: 'Narrower, upright torso' },
    ],
  },
  'side-plank-clamshell': {
    id: 'side-plank-clamshell',
    name: 'Side Plank Clamshell',
    category: 'isolation',
    cue: 'Side plank position, open knees like clamshell, squeeze glute med at top',
    youtubeUrl: 'https://www.youtube.com/watch?v=H0_DAcSFQ5A',
    substitutions: [
      { name: 'Side Plank with Clamshell', why: 'Same, just tempo variation' },
      { name: 'Banded Clamshell (lying)', why: 'Lying position, less core demand' },
      { name: 'Monster Walk (banded)', why: 'Standing, glute med focus' },
    ],
  },
  'weighted-bar-dip': {
    id: 'weighted-bar-dip',
    name: 'Weighted Bar Dip',
    category: 'calisthenics',
    cue: 'Lean forward at bottom, lower until tricep stretch, press to lockout',
    youtubeUrl: 'https://www.youtube.com/watch?v=yN6Q1UI_xkE',
    substitutions: [
      { name: 'Ring Dip', why: 'More instability, rings required' },
      { name: 'Bench Dip', why: 'Easier, back-friendly' },
      { name: 'Machine Dip', why: 'Guided, adjustable assist' },
    ],
  },
  'ring-row': {
    id: 'ring-row',
    name: 'Ring Row',
    category: 'compound',
    cue: 'Lean into rings, row to chest, squeeze shoulder blades together',
    youtubeUrl: 'https://www.youtube.com/watch?v=Z5A5H3f4uLw',
    substitutions: [
      { name: 'TRX Row', why: 'Similar instability, different straps' },
      { name: 'Inverted Row (bar)', why: 'Bodyweight,卧推架 or bar' },
      { name: 'Seated Cable Row', why: 'Cable, constant tension' },
    ],
  },
  'weighted-ring-push-up': {
    id: 'weighted-ring-push-up',
    name: 'Weighted Ring Push Up',
    category: 'calisthenics',
    cue: 'Rings turned out 45°, lower to chest, press through full extension',
    youtubeUrl: 'https://www.youtube.com/watch?v=b0xFZ2HtENM',
    substitutions: [
      { name: 'Ring Push Up (bodyweight)', why: 'No weight, easier' },
      { name: 'Dumbbell Bench Press', why: 'Weighted, lying down' },
      { name: 'Push-Up (feet elevated)', why: 'More load shift to anterior deltoid' },
    ],
  },
  'tall-plank-rings': {
    id: 'tall-plank-rings',
    name: 'Tall Plank on Rings',
    category: 'mobility',
    cue: 'Rings turned out, hold top plank position, fight sag and pike',
    youtubeUrl: 'https://www.youtube.com/watch?v=BSpCdDY9d3E',
    substitutions: [
      { name: 'Plank (floor)', why: 'Easier, stable surface' },
      { name: 'Ring Support Hold', why: 'Top position of dip, no pike' },
      { name: 'Dead Bug', why: 'Lying, anti-extension core' },
    ],
  },
  'dead-hang': {
    id: 'dead-hang',
    name: 'Dead Hang',
    category: 'mobility',
    cue: 'Hang from bar, squeeze shoulder blades down, breathe and relax',
    youtubeUrl: 'https://www.youtube.com/watch?v=4Eu-EK-P2KI',
    isTimeBased: true,
    substitutions: [
      { name: 'Active Hang', why: 'Pull shoulders down actively' },
      { name: 'Lat Hang (band assisted)', why: 'More passive stretch' },
      { name: 'Flexed Arm Hang', why: 'Chin up, less strict' },
    ],
  },
  'low-row': {
    id: 'low-row',
    name: 'Low Row (cable or DB)',
    category: 'compound',
    cue: 'Pull to lower chest/abdomen, squeeze lats, control the negative',
    youtubeUrl: 'https://www.youtube.com/watch?v=GZ9f3vT3QkY',
    substitutions: [
      { name: 'Seated Cable Row', why: 'Seated, more back focus' },
      { name: 'Chest-Supported DB Row', why: 'Less lower back, DB option' },
      { name: 'Barbell Row', why: 'Heavy, compound' },
    ],
  },
  'cable-y-raise': {
    id: 'cable-y-raise',
    name: 'Cable Y-Raise',
    category: 'isolation',
    cue: 'Pull cable in Y-shape, lead with thumbs, feel rear delt + traps',
    youtubeUrl: 'https://www.youtube.com/watch?v=T7WwvZ7z6U8',
    substitutions: [
      { name: 'Dumbbell Y-Raise', why: 'Dumbbells, free motion' },
      { name: 'Face Pull', why: 'More rear delt emphasis' },
      { name: 'Band Pull-Apart', why: 'Light, warm-up friendly' },
    ],
  },
  'front-lever-hold': {
    id: 'front-lever-hold',
    name: 'Tuck Front Lever Hold',
    category: 'calisthenics',
    cue: 'Tuck hard, retract scapulae, hold horizontal line — no sag or pike',
    youtubeUrl: 'https://www.youtube.com/watch?v=eXYCKTwK9EI',
    isTimeBased: true,
    substitutions: [
      { name: 'Advanced Tuck FL Hold', why: 'Longer lever, harder' },
      { name: 'Hanging Knee Raise (tucked)', why: 'Simpler hold, build hollow body' },
      { name: 'Dragon Flag', why: 'Bench-based, same core demand' },
    ],
  },
  'ring-fly': {
    id: 'ring-fly',
    name: 'Ring Fly',
    category: 'isolation',
    cue: 'Start in support hold, lower to rings, fly arms wide, press back up',
    youtubeUrl: 'https://www.youtube.com/watch?v=5t0CgvZFIkE',
    substitutions: [
      { name: 'Pec Deck (machine)', why: 'Guided, chest focus' },
      { name: 'Cable Crossover', why: 'Constant tension, adjustable' },
      { name: 'Push-Up Variation', why: 'Bodyweight, floor-based' },
    ],
  },
  'ab-roller': {
    id: 'ab-roller',
    name: 'Ab Roller',
    category: 'isolation',
    cue: 'Brace core, roll out until back is flat, pull back to start',
    youtubeUrl: 'https://www.youtube.com/watch?v=pth9p3-hqOo',
    substitutions: [
      { name: 'Plank (front)', why: 'Core stability, no rolling' },
      { name: 'Hanging Knee Raise', why: 'Hanging, more load' },
      { name: 'Dead Bug', why: 'Lying, anti-extension' },
    ],
  },
  'power-snatch': {
    id: 'power-snatch',
    name: 'Power Snatch',
    category: 'explosive',
    cue: 'Big shrug and triple extension, catch in partial squat, stand to finish',
    youtubeUrl: 'https://www.youtube.com/watch?v=CHARTj0E9aI',
    substitutions: [
      { name: 'Hang Snatch', why: 'From knee, same movement' },
      { name: 'Trophy Snatch', why: 'Easier, pause at top' },
      { name: 'Dumbbell Snatch', why: 'DB, less technical' },
    ],
  },
  'zercher-squat': {
    id: 'zercher-squat',
    name: 'Zercher Squat',
    category: 'compound',
    cue: 'Bar in crook of elbows, brace hard, squat to depth, drive up tall',
    youtubeUrl: 'https://www.youtube.com/watch?v=5r3L_3eJ7Xk',
    substitutions: [
      { name: 'Goblet Squat', why: 'Front load, similar pattern' },
      { name: 'Front Squat', why: 'Bar on clavicles, more quad' },
      { name: 'Belt Squat', why: 'Loaded, no spinal compression' },
    ],
  },
  'goblet-rdl': {
    id: 'goblet-rdl',
    name: 'Goblet RDL',
    category: 'compound',
    cue: 'KB/DB at chest, hinge at hips, feel hamstrings stretch, drive hips forward',
    youtubeUrl: 'https://www.youtube.com/watch?v=IM7VQTJ-pjA',
    substitutions: [
      { name: 'Romanian Deadlift', why: 'Barbell, heavier load' },
      { name: 'Dumbbell RDL', why: 'Dumbbells, no grip issue' },
      { name: 'Single-Leg RDL', why: 'Unilateral, balance challenge' },
    ],
  },
  'ball-slam': {
    id: 'ball-slam',
    name: 'Ball Slams',
    category: 'conditioning',
    cue: 'Big arc overhead, slam med ball hard, catch or let bounce, repeat',
    youtubeUrl: 'https://www.youtube.com/watch?v=gNWBGsjFeWo',
    substitutions: [
      { name: 'Med Ball Overhead Slam', why: 'Same but different arc' },
      { name: 'Battle Rope Slams', why: 'Sustained power output' },
      { name: 'Kettlebell Swing', why: 'Hip hinge, faster tempo' },
    ],
  },
  'suitcase-carry': {
    id: 'suitcase-carry',
    name: 'Suitcase Carry',
    category: 'carry',
    cue: 'Single arm KB carry, stand tall, fight lateral flexion, switch hands',
    youtubeUrl: 'https://www.youtube.com/watch?v=7IaAfH3h5F0',
    substitutions: [
      { name: "Farmer's Carry", why: 'Both arms, heavier load' },
      { name: 'Overhead Carry', why: 'Press position, shoulder stability' },
      { name: 'Single-Leg Deadlift Carry', why: 'BOSU or beam, balance' },
    ],
  },
  'single-arm-db-row': {
    id: 'single-arm-db-row',
    name: 'Single Arm DB Row',
    category: 'compound',
    cue: 'One hand on bench, row DB to hip, squeeze at top, control negative',
    youtubeUrl: 'https://www.youtube.com/watch?v=Ej5F0Y8VqhQ',
    substitutions: [
      { name: 'Chest-Supported DB Row', why: 'Both arms, chest supported' },
      { name: 'Seated Cable Row', why: 'Cable, constant tension' },
      { name: 'Renegade Row', why: 'Plank position, core + row' },
    ],
  },
}

export const CATEGORY_COLORS: Record<ExerciseCategory, string> = {
  compound: 'text-blue-500 border-blue-500/30',
  isolation: 'text-purple-500 border-purple-500/30',
  explosive: 'text-red-500 border-red-500/30',
  calisthenics: 'text-primary border-primary/30',
  conditioning: 'text-orange-500 border-orange-500/30',
  carry: 'text-amber-600 border-amber-600/30',
  mobility: 'text-cyan-500 border-cyan-500/30',
  plyometric: 'text-rose-500 border-rose-500/30',
}

export const CATEGORY_LABELS: Record<ExerciseCategory, string> = {
  compound: 'Compound',
  isolation: 'Isolation',
  explosive: 'Explosive',
  calisthenics: 'Calisthenics',
  conditioning: 'Conditioning',
  carry: 'Carry',
  mobility: 'Mobility',
  plyometric: 'Plyometric',
}
