import type { Exercise, ExerciseCategory } from '@/types/workout'

export const EXERCISES: Record<string, Exercise> = {
  'barbell-back-squat': {
    id: 'barbell-back-squat',
    name: 'Barbell Back Squat',
    category: 'compound',
    youtubeUrl: 'https://www.youtube.com/watch?v=bEv6CCg2BC8',
    substitutions: [
      { name: 'Goblet Squat', why: 'Lighter load, great for mobility' },
      { name: 'Belt Squat', why: 'No spinal compression, pure legs' },
      { name: 'Leg Press', why: 'Machine option, back-friendly' },
    ],
  },
  'romanian-deadlift': {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    category: 'compound',
    youtubeUrl: 'https://www.youtube.com/watch?v=7j-2w4-P14I',
    substitutions: [
      { name: 'Dumbbell RDL', why: 'Easier setup, no bar grip issues' },
      { name: 'Single-Leg RDL', why: 'Unilateral, balance challenge' },
      { name: '45° Back Extension', why: 'Machine option, no grip fatigue' },
    ],
  },
  'bulgarian-split-squat': {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    category: 'compound',
    youtubeUrl: 'https://www.youtube.com/watch?v=-4LVK1crLSw',
    substitutions: [
      { name: 'Reverse Lunge', why: 'Less balance demand' },
      { name: 'Walking Lunge', why: 'Dynamic, athletic' },
      { name: 'Step-Up (DB)', why: 'Single-leg, lower back friendly' },
    ],
  },
  'walking-lunge': {
    id: 'walking-lunge',
    name: 'Walking Lunge (DB or KB)',
    category: 'compound',
    youtubeUrl: 'https://www.youtube.com/watch?v=eFWCn5iEbTU',
    substitutions: [
      { name: 'Reverse Lunge', why: 'Less knee stress, stationary' },
      { name: 'Bulgarian Split Squat', why: 'More stretch, stationary' },
      { name: 'Lateral Lunge (DB)', why: 'Frontal plane, adductor work' },
    ],
  },
  'nordic-hamstring-curl': {
    id: 'nordic-hamstring-curl',
    name: 'Nordic Hamstring Curl',
    category: 'isolation',
    youtubeUrl: 'https://www.youtube.com/watch?v=htyDuCI8cm8',
    substitutions: [
      { name: 'Seated Leg Curl', why: 'Machine option, easier to load' },
      { name: 'Slider Leg Curl', why: 'Floor-based, bodyweight' },
      { name: 'Swiss Ball Hamstring Curl', why: 'Stability challenge' },
    ],
  },
  'barbell-hip-thrust': {
    id: 'barbell-hip-thrust',
    name: 'Barbell Hip Thrust',
    category: 'compound',
    youtubeUrl: 'https://www.youtube.com/watch?v=xDmFkJxPzeM',
    substitutions: [
      { name: 'Glute Bridge (barbell)', why: 'Same movement, off the floor' },
      { name: 'Cable Pull-Through', why: 'Standing, constant tension' },
      { name: 'Hip Thrust Machine', why: 'Machine version, easier setup' },
    ],
  },
  'conventional-deadlift': {
    id: 'conventional-deadlift',
    name: 'Conventional Deadlift',
    category: 'compound',
    youtubeUrl: 'https://www.youtube.com/watch?v=op9kVnSso6Q',
    substitutions: [
      { name: 'Trap Bar Deadlift', why: 'More upright, easier on lower back' },
      { name: 'Sumo Deadlift', why: 'Wider stance, more quads/adductors' },
      { name: 'Romanian Deadlift', why: 'Less floor pull, more hinge' },
    ],
  },
  'snatch-grip-rdl': {
    id: 'snatch-grip-rdl',
    name: 'Snatch-Grip Romanian Deadlift',
    category: 'compound',
    youtubeUrl: 'https://www.youtube.com/watch?v=0ed2L2XIO9E',
    substitutions: [
      { name: 'Romanian Deadlift', why: 'Standard grip width' },
      { name: 'Dumbbell RDL', why: 'Dumbbells, no grip issue' },
      { name: '45° Back Extension', why: 'Weighted, back-friendly' },
    ],
  },
  'goblet-squat': {
    id: 'goblet-squat',
    name: 'Goblet Squat',
    category: 'compound',
    youtubeUrl: 'https://www.youtube.com/watch?v=MxsFDhcyFyE',
    substitutions: [
      { name: 'Bodyweight Squat', why: 'No equipment needed' },
      { name: 'Dumbbell Front Squat', why: 'Heavier load, same pattern' },
      { name: 'Leg Press', why: 'Machine alternative' },
    ],
  },
  'weighted-pull-up': {
    id: 'weighted-pull-up',
    name: 'Weighted Pull-Up',
    category: 'calisthenics',
    youtubeUrl: 'https://www.youtube.com/watch?v=HuuyDNGrCI8',
    substitutions: [
      { name: 'Lat Pulldown', why: 'Machine, adjustable load' },
      { name: 'Chin-Up (supinated)', why: 'More biceps, easier' },
      { name: 'Band-Assisted Pull-Up', why: 'Reduced bodyweight' },
    ],
  },
  'ring-push-up': {
    id: 'ring-push-up',
    name: 'Ring Push-Up',
    category: 'calisthenics',
    youtubeUrl: 'https://www.youtube.com/watch?v=b0xFZ2HtENM',
    substitutions: [
      { name: 'Push-Up (standard)', why: 'No equipment needed' },
      { name: 'Dumbbell Bench Press', why: 'Weighted, lying down' },
      { name: 'TRX Push-Up', why: 'TRX straps, similar instability' },
    ],
  },
  'ring-dip': {
    id: 'ring-dip',
    name: 'Dip (weighted if possible)',
    category: 'calisthenics',
    youtubeUrl: 'https://www.youtube.com/watch?v=yN6Q1UI_xkE',
    substitutions: [
      { name: 'Bench Dip', why: 'Easier, bodyweight' },
      { name: 'Push-Up (close grip)', why: 'Floor-based, no bars' },
      { name: 'Machine Dip', why: 'Assisted, adjustable' },
    ],
  },
  'chest-supported-db-row': {
    id: 'chest-supported-db-row',
    name: 'Chest-Supported Dumbbell Row',
    category: 'compound',
    youtubeUrl: 'https://www.youtube.com/watch?v=RpODPuNtZS8',
    substitutions: [
      { name: 'Barbell Bent-Over Row', why: 'Heavier, compound' },
      { name: 'Seated Cable Row', why: 'Constant tension, cables' },
      { name: 'Single-Arm DB Row', why: 'Unilateral, anti-rotation' },
    ],
  },
  'seated-cable-row': {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    category: 'compound',
    youtubeUrl: 'https://www.youtube.com/watch?v=sP_4vybjVJs',
    substitutions: [
      { name: 'Chest-Supported Dumbbell Row', why: 'Free weight, DB option' },
      { name: 'Barbell Bent-Over Row', why: 'Compound, heavy' },
      { name: 'Machine Row', why: 'Guided, stable' },
    ],
  },
  'cable-face-pull': {
    id: 'cable-face-pull',
    name: 'Cable Face Pull',
    category: 'isolation',
    youtubeUrl: 'https://www.youtube.com/watch?v=ljgqer1ZpXg',
    substitutions: [
      { name: 'Band Face Pull', why: 'Band option, portable' },
      { name: 'Reverse Fly (DB)', why: 'Dumbbells, rear delt focus' },
      { name: 'Band Pull-Apart', why: 'Light, warmup or finisher' },
    ],
  },
  'barbell-bench-press': {
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    category: 'compound',
    youtubeUrl: 'https://www.youtube.com/watch?v=rT7DgCr-3pg',
    substitutions: [
      { name: 'Dumbbell Bench Press', why: 'Better ROM, independent arms' },
      { name: 'Dumbbell Incline Press', why: 'Upper chest emphasis' },
      { name: 'Floor Press (DB or BB)', why: 'Shorter ROM, shoulder safe' },
    ],
  },
  'overhead-press': {
    id: 'overhead-press',
    name: 'Overhead Press',
    category: 'compound',
    youtubeUrl: 'https://www.youtube.com/watch?v=_RlRDWO2jfg',
    substitutions: [
      { name: 'Dumbbell Shoulder Press', why: 'Independent arms, seated option' },
      { name: 'Landmine Press', why: 'Angled, shoulder-friendly' },
      { name: 'Arnold Press', why: 'Rotation, more delt activation' },
    ],
  },
  'landmine-press': {
    id: 'landmine-press',
    name: 'Landmine Press',
    category: 'compound',
    youtubeUrl: 'https://www.youtube.com/shorts/gH7PDepHNck',
    substitutions: [
      { name: 'Overhead Press', why: 'Full overhead, barbell' },
      { name: 'Dumbbell Shoulder Press', why: 'Seated or standing, DBs' },
      { name: 'Machine Shoulder Press', why: 'Guided path, stable' },
    ],
  },
  'db-incline-press': {
    id: 'db-incline-press',
    name: 'Dumbbell Incline Press',
    category: 'compound',
    youtubeUrl: 'https://www.youtube.com/watch?v=0t6z4Q2iHQA',
    substitutions: [
      { name: 'Barbell Incline Press', why: 'Heavier load option' },
      { name: 'Machine Incline Press', why: 'No stabilization needed' },
      { name: 'Landmine Press (kneeling)', why: 'Angled press, core engaged' },
    ],
  },
  'db-hammer-curl': {
    id: 'db-hammer-curl',
    name: 'Dumbbell Hammer Curl',
    category: 'isolation',
    youtubeUrl: 'https://www.youtube.com/watch?v=7jqi2qWAUJk',
    substitutions: [
      { name: 'Barbell Curl', why: 'Heavier, bilateral' },
      { name: 'Cable Curl', why: 'Constant tension' },
      { name: 'Incline DB Curl', why: 'Stretched position, long head' },
    ],
  },
  'db-lateral-raise': {
    id: 'db-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    category: 'isolation',
    youtubeUrl: 'https://www.youtube.com/watch?v=-hyAJdSFzT4',
    substitutions: [
      { name: 'Cable Lateral Raise', why: 'Constant tension at bottom' },
      { name: 'Machine Lateral Raise', why: 'Guided, easier to load' },
      { name: 'Band Lateral Raise', why: 'Portable, good for pump' },
    ],
  },
  'overhead-tricep-extension': {
    id: 'overhead-tricep-extension',
    name: 'Overhead Tricep Extension (cable)',
    category: 'isolation',
    youtubeUrl: 'https://www.youtube.com/watch?v=IaJWPqP-Bjo',
    substitutions: [
      { name: 'Skull Crusher (BB/EZ)', why: 'Barbell, heavy triceps' },
      { name: 'Dumbbell Overhead Extension', why: 'DB alternative' },
      { name: 'Close-Grip Bench Press', why: 'Compound tricep builder' },
    ],
  },
  'box-jump': {
    id: 'box-jump',
    name: 'Box Jump (step down)',
    category: 'plyometric',
    youtubeUrl: 'https://www.youtube.com/watch?v=aDZoErlL1LQ',
    substitutions: [
      { name: 'Squat Jump', why: 'No box needed' },
      { name: 'Broad Jump', why: 'Horizontal power' },
      { name: 'Depth Jump', why: 'Reactive, advanced' },
    ],
  },
  'broad-jump': {
    id: 'broad-jump',
    name: 'Broad Jump',
    category: 'plyometric',
    youtubeUrl: 'https://www.youtube.com/watch?v=96zJo3nlmHI',
    substitutions: [
      { name: 'Box Jump', why: 'Vertical power' },
      { name: 'Squat Jump', why: 'Vertical, no distance needed' },
      { name: 'Kettlebell Swing', why: 'Hip power, loaded' },
    ],
  },
  'clap-push-up': {
    id: 'clap-push-up',
    name: 'Clap Push-Up',
    category: 'plyometric',
    youtubeUrl: 'https://www.youtube.com/watch?v=EYwWCgM198U',
    substitutions: [
      { name: 'Explosive Push-Up', why: 'Hands leave, no clap' },
      { name: 'Med Ball Chest Pass', why: 'Wall throw, upper body power' },
      { name: 'Band-Resisted Push-Up', why: 'Loaded push, explosive' },
    ],
  },
  'depth-drop': {
    id: 'depth-drop',
    name: 'Depth Drop',
    category: 'plyometric',
    youtubeUrl: 'https://www.youtube.com/watch?v=DZrJpNfmIHQ',
    substitutions: [
      { name: 'Box Jump', why: 'Concentric focus' },
      { name: 'Drop Landing', why: 'Absorb only, less reactive' },
      { name: 'Broad Jump', why: 'Horizontal, no box' },
    ],
  },
  'sprint-intervals': {
    id: 'sprint-intervals',
    name: 'Sprint Intervals',
    category: 'conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=sWoQS_JDHoU',
    substitutions: [
      { name: 'Bike Sprint Intervals', why: 'Low impact, same effort' },
      { name: 'Rowing Sprint Intervals', why: 'Full body, indoor' },
      { name: 'Hill Sprints', why: 'Natural incline, less hamstring risk' },
    ],
  },
  'kettlebell-swing': {
    id: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    category: 'explosive',
    youtubeUrl: 'https://www.youtube.com/watch?v=jYtimecuwuw',
    substitutions: [
      { name: 'Dumbbell Swing', why: 'DB substitute' },
      { name: 'Hip Thrust (explosive)', why: 'Loaded hip extension' },
      { name: 'Cable Pull-Through', why: 'Similar hinge, constant tension' },
    ],
  },
  'farmers-carry': {
    id: 'farmers-carry',
    name: "Farmer's Carry",
    category: 'carry',
    youtubeUrl: 'https://www.youtube.com/watch?v=IWxerVP5eps',
    substitutions: [
      { name: 'Suitcase Carry', why: 'Single arm, anti-lateral flexion' },
      { name: 'Overhead Carry', why: 'Shoulder stability challenge' },
      { name: 'Trap Bar Carry', why: 'Heavier load, centered' },
    ],
  },
  'turkish-get-up': {
    id: 'turkish-get-up',
    name: 'Turkish Get-Up',
    category: 'conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=jFK8FOiLa_M',
    substitutions: [
      { name: 'Windmill', why: 'Similar stability, simpler' },
      { name: 'Half Get-Up', why: 'First half only, easier' },
      { name: 'Overhead Carry', why: 'Stability + movement' },
    ],
  },
  'devils-press': {
    id: 'devils-press',
    name: "Devil's Press (DB)",
    category: 'conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=Cwxmji-3k40',
    substitutions: [
      { name: 'Dumbbell Thruster', why: 'Squat to press, simpler' },
      { name: 'Burpee', why: 'Bodyweight, no DBs' },
      { name: 'Man Maker', why: 'Adds clean and press' },
    ],
  },
  'renegade-row': {
    id: 'renegade-row',
    name: 'Renegade Row',
    category: 'compound',
    youtubeUrl: 'https://www.youtube.com/watch?v=eGhLfe0feEs',
    substitutions: [
      { name: 'Plank Row (single DB)', why: 'One arm at a time' },
      { name: 'Push-Up + Row (alternating)', why: 'Same but separate reps' },
      { name: 'Man Maker', why: 'Adds clean and press' },
    ],
  },
  'burpee-to-pull-up': {
    id: 'burpee-to-pull-up',
    name: 'Burpee to Pull-Up',
    category: 'conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=RWysgOhr0vM',
    substitutions: [
      { name: 'Burpee', why: 'No pull-up bar needed' },
      { name: "Devil's Press (DB)", why: 'DB-loaded full body' },
      { name: 'Thruster', why: 'Squat to press combo' },
    ],
  },
  'med-ball-overhead-slam': {
    id: 'med-ball-overhead-slam',
    name: 'Med Ball Overhead Slam',
    category: 'explosive',
    youtubeUrl: 'https://www.youtube.com/watch?v=gNWBGsjFeWo',
    substitutions: [
      { name: 'Ball Slam', why: 'Same but downward emphasis' },
      { name: 'Kettlebell Swing', why: 'Hip power, no slam' },
      { name: 'Battle Rope Slams', why: 'Sustained power output' },
    ],
  },
  'rotational-wall-throw': {
    id: 'rotational-wall-throw',
    name: 'Rotational Wall Throw',
    category: 'conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=IhIi-lDzHXw',
    substitutions: [
      { name: 'Med Ball Chest Pass', why: 'Linear, upper body' },
      { name: 'Landmine Press', why: 'Rotational component' },
    ],
  },
  'front-lever-progression': {
    id: 'front-lever-progression',
    name: 'Front Lever Progression',
    category: 'calisthenics',
    youtubeUrl: 'https://www.youtube.com/watch?v=eXYCKTwK9EI',
    substitutions: [
      { name: 'Hanging Knee Raise (tucked hold)', why: 'Simpler hold, build up' },
      { name: 'Ring Row (feet elevated)', why: 'Similar pull angle, easier' },
      { name: 'Dragon Flag (progression)', why: 'Bench-based, same core demand' },
    ],
  },
  'hollow-body-hold': {
    id: 'hollow-body-hold',
    name: 'Hollow Body Hold',
    category: 'mobility',
    youtubeUrl: 'https://www.youtube.com/watch?v=YceIIdhzDPo',
    substitutions: [
      { name: 'Dead Bug', why: 'Easier, alternating limbs' },
      { name: 'Plank', why: 'Prone, simpler setup' },
      { name: 'Ab Wheel Rollout', why: 'Rolling core challenge' },
    ],
  },
  'hanging-knee-raise': {
    id: 'hanging-knee-raise',
    name: 'Hanging Knee Raise',
    category: 'calisthenics',
    youtubeUrl: 'https://www.youtube.com/watch?v=RD_A-Z15ER4',
    substitutions: [
      { name: 'Hanging Leg Raise', why: 'Harder, straight legs' },
      { name: "Captain's Chair Knee Raise", why: 'Padded support' },
      { name: 'Lying Leg Raise', why: 'Floor-based, no bar needed' },
    ],
  },
  'bear-crawl': {
    id: 'bear-crawl',
    name: 'Bear Crawl',
    category: 'conditioning',
    youtubeUrl: 'https://www.youtube.com/watch?v=vg5hegN6pk0',
    substitutions: [
      { name: 'Bear Crawl Hold', why: 'Static, no movement' },
      { name: 'Plank to Push-Up', why: 'Dynamic, tricep emphasis' },
    ],
  },
  'side-plank': {
    id: 'side-plank',
    name: 'Side Plank',
    category: 'mobility',
    youtubeUrl: 'https://www.youtube.com/watch?v=茉莉',
    substitutions: [
      { name: 'Copenhagen Plank', why: 'Adductor emphasis, harder' },
      { name: 'Pallof Press', why: 'Cable anti-rotation' },
      { name: 'Suitcase Carry', why: 'Walking anti-lateral flexion' },
    ],
  },
  'copenhagen-plank': {
    id: 'copenhagen-plank',
    name: 'Copenhagen Plank',
    category: 'mobility',
    substitutions: [
      { name: 'Side Plank', why: 'Easier, no bench needed' },
      { name: 'Side Plank with Hip Dip', why: 'Dynamic oblique' },
    ],
  },
  'single-leg-calf-raise': {
    id: 'single-leg-calf-raise',
    name: 'Single-Leg Calf Raise',
    category: 'isolation',
    youtubeUrl: 'https://www.youtube.com/watch?v=_gEx2ijsmNM',
    substitutions: [
      { name: 'Seated Calf Raise', why: 'Soleus emphasis, machine' },
      { name: 'Standing Calf Raise (machine)', why: 'Both legs, heavier load' },
    ],
  },
}

export const CATEGORY_COLORS: Record<ExerciseCategory, string> = {
  compound: 'text-blue-500 border-blue-500/30',
  isolation: 'text-purple-500 border-purple-500/30',
  explosive: 'text-red-500 border-red-500/30',
  calisthenics: 'text-primary border-primary/30',
  conditioning: 'text-orange-500 border-orange-500/30',
  carry: 'text-amber-600 border-amber-600/30',
  mobility: 'text-cyan-500 border-cyan-500/30',
  plyometric: 'text-rose-500 border-rose-500/30',
}

export const CATEGORY_LABELS: Record<ExerciseCategory, string> = {
  compound: 'Compound',
  isolation: 'Isolation',
  explosive: 'Explosive',
  calisthenics: 'Calisthenics',
  conditioning: 'Conditioning',
  carry: 'Carry',
  mobility: 'Mobility',
  plyometric: 'Plyometric',
}
